In [259]:
import pandas as pd

In [260]:
cars_df = pd.read_csv('CSV_Files/cars.csv')

In [261]:
final_cars_df = cars_df[cars_df['Identification.Make'].isna() == False]
final_cars_df

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification,Identification.ID,Identification.Make,Identification.Model Year,Identification.Year,Engine Information.Engine Statistics.Horsepower,Engine Information.Engine Statistics.Torque
0,140,143,202,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission,2009 Audi A3 3.2,Audi,2009 Audi A3,2009,250,236
1,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T AT,Audi,2009 Audi A3,2009,200,207
2,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission,2009 Audi A3 2.0 T,Audi,2009 Audi A3,2009,200,207
3,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
4,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5071,13,253,201,Front-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,18,Gasoline,25,Automatic transmission,2012 Honda Pilot EX-L,Honda,2012 Honda Pilot,2012,250,253
5072,141,249,108,All-wheel drive,Lamborghini 5.2L 10 cylinder 552 hp 398 ft-lbs,True,6,6 Speed Manual,12,Gasoline,20,Manual transmission,2012 Lamborghini Gallardo Coupe LP 560-4,Lamborghini,2012 Lamborghini Gallardo Coup,2012,552,398
5073,160,249,108,All-wheel drive,Lamborghini 5.2L 10 cylinder 552 hp 398 ft-lbs,True,6,6 Speed Manual,12,Gasoline,20,Manual transmission,2012 Lamborghini Gallardo LP 560-4 Spyder,Lamborghini,2012 Lamborghini Gallardo Spyder,2012,552,398
5074,200,210,110,Rear-wheel drive,BMW 3.0L 6 cylinder 315hp 330 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,17,Gasoline,25,Automatic transmission,2012 BMW 740i Sedan,BMW,2012 BMW 7 Series,2012,315,330
5075,200,94,110,Rear-wheel drive,BMW 3.0L 6 cylinder 315hp 330 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,17,Gasoline,25,Automatic transmission,2012 BMW 740Li Sedan,BMW,2012 BMW 7 Series,2012,315,330

In [279]:
final_cars_df.astype({'Length': 'float64', 'Width': 'float64', 'Height': 'float64'}).dtypes

Height           float64
Length           float64
Width            float64
Drivetrain        object
Engine_Type       object
Hybrid              bool
Gears              int64
Transmission      object
City_MPG           int64
Fuel_Type         object
Highway_MPG        int64
Cassification     object
Car Name          object
Make              object
Model             object
Year               int64
Horsepower         int64
Torque             int64
dtype: object

In [280]:
#final_cars_df.count()

final_cars_df.rename(columns={'Dimensions.Height': 'Height',
                   'Dimensions.Length': 'Length',
                   'Dimensions.Width':'Width',
                   'Engine Information.Driveline': 'Drivetrain',
                   'Engine Information.Engine Type':'Engine_Type',
                   'Engine Information.Hybrid' : 'Hybrid',
                   'Engine Information.Number of Forward Gears': 'Gears',
                   'Engine Information.Transmission': 'Transmission',
                   'Fuel Information.City mpg' : 'City_MPG',
                   'Fuel Information.Highway mpg' : 'Highway_MPG',
                   'Fuel Information.Fuel Type': 'Fuel_Type',
                   'Identification.Classification': 'Cassification', 
                   'Identification.ID': 'Car Name',
                   'Identification.Make': 'Make',
                   'Identification.Model Year' : 'Model',
                   'Identification.Year' : 'Year',
                   'Engine Information.Engine Statistics.Horsepower': 'Horsepower',
                   'Engine Information.Engine Statistics.Torque': 'Torque'},  inplace=True)
final_cars_df.columns

Index(['Height', 'Length', 'Width', 'Drivetrain', 'Engine_Type', 'Hybrid',
       'Gears', 'Transmission', 'City_MPG', 'Fuel_Type', 'Highway_MPG',
       'Cassification', 'Car Name', 'Make', 'Model', 'Year', 'Horsepower',
       'Torque'],
      dtype='object')

In [281]:
cars = pd.DataFrame(final_cars_df)
cars.head()

,Height,Length,Width,Drivetrain,Engine_Type,Hybrid,Gears,Transmission,City_MPG,Fuel_Type,Highway_MPG,Cassification,Car Name,Make,Model,Year,Horsepower,Torque
0,140,143,202,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission,2009 Audi A3 3.2,Audi,2009 Audi A3,2009,250,236
1,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T AT,Audi,2009 Audi A3,2009,200,207
2,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission,2009 Audi A3 2.0 T,Audi,2009 Audi A3,2009,200,207
3,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
4,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207

In [282]:
car_data_df = pd.read_csv('CSV_Files/car_data.csv')
car_data_df.head()

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450

In [283]:
final_car_data_df = cleaned_df[cleaned_df['make'].isna() == False]
#final_car_data_df.columns

In [284]:
final_car_data_df.dtypes

make                  object
fuel_type             object
aspiration            object
num_of_doors          object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_of_cylinders      object
engine_size            int64
fuel_system           object
compression_ratio    float64
horsepower            object
peak_rpm              object
city_mpg               int64
highway_mpg            int64
price                 object
dtype: object

In [286]:
#final_cars_df.count()

final_car_data_df.rename(columns={'make':'Make', 
                              'fuel_type' :'Engine_Type', 
                              'aspiration' : 'Aspiration', 
                              'num_of_doors' : 'Number of Doors', 
                              'body_style' : "Body Style",
                              'drive_wheels': 'Drivetrain',
                              'engine_location' : 'Engine_Location',
                              'wheel_base' : 'Wheel Base', 
                              'length': 'Length', 
                              'width':'Width',
                              'height' : 'Height', 
                              'curb_weight' : 'Weight', 
                              'engine_type' : 'Engine Type', 
                              'num_of_cylinders' : 'Numner_Cylinders',
                              'engine_size': 'Engine Size', 
                              'fuel_system' : 'Fuel System', 
                              'compression_ratio' : 'Compression Ratio', 
                              'horsepower' : 'Horsepower',
                              'peak_rpm' : 'Peak_RPM', 
                              'city_mpg' : 'City_MPG', 
                              'highway_mpg' : 'Highway_MPG', 
                              'price' : 'Price'},  inplace=True)
final_car_data_df.dtypes

Make                  object
Engine_Type           object
Aspiration            object
Number of Doors       object
Body Style            object
Drivetrain            object
Engine_Location       object
Wheel Base           float64
Length               float64
Width                float64
Height               float64
Weight                 int64
Engine Type           object
Numner_Cylinders      object
Engine Size            int64
Fuel System           object
Compression Ratio    float64
Horsepower            object
Peak_RPM              object
City_MPG               int64
Highway_MPG            int64
Price                 object
dtype: object

In [287]:
car = pd.DataFrame(final_car_data_df)
car

,Make,Engine_Type,Aspiration,Number of Doors,Body Style,Drivetrain,Engine_Location,Wheel Base,Length,Width,...,Engine Type,Numner_Cylinders,Engine Size,Fuel System,Compression Ratio,Horsepower,Peak_RPM,City_MPG,Highway_MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [289]:
final_df = pd.merge(cars, car, on=['Make', 
                                   'Engine_Type', 
                                   'Drivetrain', 
                                   'Length', 
                                   'Width', 
                                   'Height', 
                                   'City_MPG', 
                                   'Highway_MPG' ], how='outer')
final_df

,Height,Length,Width,Drivetrain,Engine_Type,Hybrid,Gears,Transmission,City_MPG,Fuel_Type,...,Wheel Base,Weight,Engine Type,Numner_Cylinders,Engine Size,Fuel System,Compression Ratio,Horsepower_y,Peak_RPM,Price
0,140.0,143.0,202.0,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6.0,6 Speed Automatic Select Shift,18,Gasoline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,140.0,143.0,202.0,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6.0,6 Speed Automatic Select Shift,22,Gasoline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,140.0,143.0,202.0,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6.0,6 Speed Manual,21,Gasoline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,140.0,143.0,202.0,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6.0,6 Speed Automatic Select Shift,21,Gasoline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,140.0,143.0,202.0,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6.0,6 Speed Automatic Select Shift,21,Gasoline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5276,55.5,188.8,68.9,rwd,gas,NaN,NaN,NaN,23,NaN,...,109.1,2952.0,ohc,four,141.0,mpfi,9.5,114,5400,16845
5277,55.5,188.8,68.8,rwd,gas,NaN,NaN,NaN,19,NaN,...,109.1,3049.0,ohc,four,141.0,mpfi,8.7,160,5300,19045
5278,55.5,188.8,68.9,rwd,gas,NaN,NaN,NaN,18,NaN,...,109.1,3012.0,ohcv,six,173.0,mpfi,8.8,134,5500,21485
5279,55.5,188.8,68.9,rwd,diesel,NaN,NaN,NaN,26,NaN,...,109.1,3217.0,ohc,six,145.0,idi,23.0,106,4800,22470
5280,55.5,188.8,68.9,rwd,gas,NaN,NaN,NaN,19,NaN,...,109.1,3062.0,ohc,four,141.0,mpfi,9.5,114,5400,22625